// <auto-generated />
using System;
using IOTGW_Admin_Panel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOTGW_Admin_Panel.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20190708074235_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Gateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<int>("NodeId");

                    b.Property<DateTime>("RecievedDateTime");

                    b.Property<string>("SourceNode")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Config")
                        .IsRequired();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<int>("GatewayId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("PostalCode");

                    b.Property<string>("Role");

                    b.Property<string>("Token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Gateway", b =>
                {
                    b.HasOne("IOTGW_Admin_Panel.Models.User", "User")
                        .WithMany("Gateways")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Message", b =>
                {
                    b.HasOne("IOTGW_Admin_Panel.Models.Node", "Node")
                        .WithMany("Messages")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IOTGW_Admin_Panel.Models.Node", b =>
                {
                    b.HasOne("IOTGW_Admin_Panel.Models.Gateway", "Gateway")
                        .WithMany("Nodes")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
